export type ColorScheme = "LIGHT_COLOR_SCHEME" | "DARK_COLOR_SCHEME";

export const LIGHT_COLOR_SCHEME: ColorScheme = "LIGHT_COLOR_SCHEME";
export const DARK_COLOR_SCHEME: ColorScheme = "DARK_COLOR_SCHEME";

export type ColorSchemePreference =
  | "SYSTEM_COLOR_SCHEME_PREFERENCE"
  | "LIGHT_COLOR_SCHEME_PREFERENCE"
  | "DARK_COLOR_SCHEME_PREFERENCE";

export const SYSTEM_COLOR_SCHEME_PREFERENCE: ColorSchemePreference =
  "SYSTEM_COLOR_SCHEME_PREFERENCE";
export const LIGHT_COLOR_SCHEME_PREFERENCE: ColorSchemePreference =
  "LIGHT_COLOR_SCHEME_PREFERENCE";
export const DARK_COLOR_SCHEME_PREFERENCE: ColorSchemePreference =
  "DARK_COLOR_SCHEME_PREFERENCE";
